spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://81.68.180.131:12002/flowable-opendoc-demo?characterEncoding=UTF-8&serverTimezone=GMT+8
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
flowable:
